In [ ]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
voc_size=1000

In [8]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[472, 878, 249, 390],
 [472, 878, 249, 686],
 [472, 89, 249, 382],
 [902, 257, 562, 872, 993],
 [902, 257, 562, 872, 493],
 [601, 472, 672, 249, 604],
 [162, 179, 1, 872]]

In [11]:
#word embedding representation
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing import pad_sequences
from tensorflow.keras.utils import pad_sequences
import numpy as np


In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 472 878 249 390]
 [  0   0   0   0 472 878 249 686]
 [  0   0   0   0 472  89 249 382]
 [  0   0   0 902 257 562 872 993]
 [  0   0   0 902 257 562 872 493]
 [  0   0   0 601 472 672 249 604]
 [  0   0   0   0 162 179   1 872]]


In [13]:
#feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile(optimizer='adam',loss='mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             10000     
                                                                 
Total params: 10000 (39.06 KB)
Trainable params: 10000 (39.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)


1/1 [==============================] - 0s 349ms/step


array([[[ 1.20756775e-03,  1.77557506e-02, -2.10802797e-02,
          2.79043652e-02,  3.17969956e-02, -3.14901024e-02,
         -1.98536161e-02, -2.94553991e-02, -4.64959033e-02,
          2.22951435e-02],
        [ 1.20756775e-03,  1.77557506e-02, -2.10802797e-02,
          2.79043652e-02,  3.17969956e-02, -3.14901024e-02,
         -1.98536161e-02, -2.94553991e-02, -4.64959033e-02,
          2.22951435e-02],
        [ 1.20756775e-03,  1.77557506e-02, -2.10802797e-02,
          2.79043652e-02,  3.17969956e-02, -3.14901024e-02,
         -1.98536161e-02, -2.94553991e-02, -4.64959033e-02,
          2.22951435e-02],
        [ 1.20756775e-03,  1.77557506e-02, -2.10802797e-02,
          2.79043652e-02,  3.17969956e-02, -3.14901024e-02,
         -1.98536161e-02, -2.94553991e-02, -4.64959033e-02,
          2.22951435e-02],
        [ 3.59842218e-02, -2.66834628e-02, -1.61781423e-02,
          1.47745498e-02,  4.21221294e-02, -2.56093629e-02,
         -3.07488441e-02, -1.51042938e-02, -1.372516

In [18]:
embedded_docs[0]


array([  0,   0,   0,   0, 472, 878, 249, 390])

In [19]:
model.predict(embedded_docs)    

1/1 [==============================] - 0s 39ms/step


array([[[ 1.20756775e-03,  1.77557506e-02, -2.10802797e-02,
          2.79043652e-02,  3.17969956e-02, -3.14901024e-02,
         -1.98536161e-02, -2.94553991e-02, -4.64959033e-02,
          2.22951435e-02],
        [ 1.20756775e-03,  1.77557506e-02, -2.10802797e-02,
          2.79043652e-02,  3.17969956e-02, -3.14901024e-02,
         -1.98536161e-02, -2.94553991e-02, -4.64959033e-02,
          2.22951435e-02],
        [ 1.20756775e-03,  1.77557506e-02, -2.10802797e-02,
          2.79043652e-02,  3.17969956e-02, -3.14901024e-02,
         -1.98536161e-02, -2.94553991e-02, -4.64959033e-02,
          2.22951435e-02],
        [ 1.20756775e-03,  1.77557506e-02, -2.10802797e-02,
          2.79043652e-02,  3.17969956e-02, -3.14901024e-02,
         -1.98536161e-02, -2.94553991e-02, -4.64959033e-02,
          2.22951435e-02],
        [ 3.59842218e-02, -2.66834628e-02, -1.61781423e-02,
          1.47745498e-02,  4.21221294e-02, -2.56093629e-02,
         -3.07488441e-02, -1.51042938e-02, -1.372516